[package]
name = "quinn_test"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47", features = ["full"] }
quinn = "0.11"
rustls = { version = "0.23", default-features = false }
rcgen = "0.14"

anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"